// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7RIXqdo12bFYR45CopKNHWFoaUnMEgsg',
    appId: '1:159053673523:web:2f0f3f4cf788319fe2df46',
    messagingSenderId: '159053673523',
    projectId: 'teste-f2e96',
    authDomain: 'teste-f2e96.firebaseapp.com',
    storageBucket: 'teste-f2e96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC73iFl0qpQyJzyAsnF4hj7QgSdO5iBqc',
    appId: '1:159053673523:android:26c2ab65a8e40e75e2df46',
    messagingSenderId: '159053673523',
    projectId: 'teste-f2e96',
    storageBucket: 'teste-f2e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoIHRLe3XLQZcLoSyWG0hMw1XbF0wHU3g',
    appId: '1:159053673523:ios:5758b1476c233398e2df46',
    messagingSenderId: '159053673523',
    projectId: 'teste-f2e96',
    storageBucket: 'teste-f2e96.firebasestorage.app',
    iosBundleId: 'com.example.vocably',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoIHRLe3XLQZcLoSyWG0hMw1XbF0wHU3g',
    appId: '1:159053673523:ios:5758b1476c233398e2df46',
    messagingSenderId: '159053673523',
    projectId: 'teste-f2e96',
    storageBucket: 'teste-f2e96.firebasestorage.app',
    iosBundleId: 'com.example.vocably',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7RIXqdo12bFYR45CopKNHWFoaUnMEgsg',
    appId: '1:159053673523:web:f566af9f911023d4e2df46',
    messagingSenderId: '159053673523',
    projectId: 'teste-f2e96',
    authDomain: 'teste-f2e96.firebaseapp.com',
    storageBucket: 'teste-f2e96.firebasestorage.app',
  );
}
